googleinterns/recomator

frontend/src/store/core_table.ts, frontend/src/store/recommendations.ts, frontend/src/store/root.ts, frontend/tests/unit/apply.spec.ts, frontend/tests/unit/recommendations.spec.ts
- Handling 'apply' being clicked for one or more recommendations.
- Launching and running status watchers for recommendations (status watchers are launched at start for all 'CLAIMED' recommendations and whenever a recommendation is applied), converted from commented out code.
- Tests for both of these
- Also, fixed the root store factory to use module store factories instead of global constants. This caused some trouble for running multiple tests, as they shared some data.
=> Frontend apply logic

frontend/src/components/CoreTable.vue, frontend/src/components/FiltersRow.vue, frontend/src/components/filters/CostFilter.vue, frontend/src/components/filters/DescriptionFilter.vue, frontend/src/components/filters/ProjectFilter.vue, frontend/src/components/filters/ResourceFilter.vue, frontend/src/components/filters/StatusFilter.vue, frontend/src/components/filters/TypeFilter.vue
- Components have been separated, so that they can be reused ( Closes: #106 ) :
- The filters form a full row in desktop mode and occupy just the first column in the mobile mode.
- I also changed "search descriptions" and "search resources" to "filter descriptions" and "filter resources" respectively, so this closes: #83 
Temporarily, it is possible to access these changes even on your phones at [s17k.github.io](https://s17k.github.io).
**After:**
=> Mobile-friendly view of filters

go.mod, go.sum, pkg/automation/disks.go, pkg/automation/instances.go, pkg/automation/service.go, pkg/automation/service_test.go
- Added waiting for non-get requests to finish before returning.
~~I will add tests once this is pre-approved, as agreed.~~
Maybe it's not too useful to actually make tests for these, as they would need to be very tightly coupled with the implementation.
As of now, these have been tested and work (verified on Pantheon individually)
- `CreateSnapshot` 
- `StopInstance`
- `DeleteDisk`
- `ChangeMachineType`
=> Waiting for googleService requests to finish

frontend/src/components/ApplyAndStatusCell.vue, frontend/src/components/Footer.vue, frontend/src/main.ts, frontend/src/store/data_model/recommendation_extra.ts, frontend/src/store/recommendations.ts, frontend/tests/unit/apply.spec.ts
- Existing recommendations are removed at the beginning of a fetch now (so that if we have authorization errors, we can easily and safely restart it):  https://github.com/googleinterns/recomator/pull/129/commits/106045e7fa1e10fe237403633e72a71808ae6c44
- We now track recommendations which need to have their status watched with a new field in `RecommendationExtra` called `needsStatusWatcher`. This allows us to just iterate through all recommendations in the watchStatus infinite loop, and easily handle the recommendations list changing. 
Requests (/apply, /watchStatus) are now sent sequentially (waiting asynchronously for the previous one to finish before sending a new one). What used to be done was sending all the requests one after another, then asynchronously handling all their …
=> Frontend - more flexible fetch & better handling of status updates

frontend/src/components/Footer.vue
- adds the 'X' button that @minorczyka suggested to clear selections and hide the footer (closes: #124)
- in my opinon a blue footer looks nicer than a yellow one; that is the primary theme colour and the colour of the header. I am open to suggestions though.
- the UX expert suggested to keep lines below 70 characters, so the summary occupies 2 or 3 lines now (closes: #103)
- simplified the margins/paddings: having too many screen size breakpoints will be hard to maintain 
**Desktop before**:
**Desktop after**:
**Mobile before**:
**Mobile after**:
=> Footer upgrade

frontend/src/components/filters/StatusFilter.vue, frontend/src/store/data_model/status_map.ts
What I observed was that page size was the factor determining the speed of statuses updates in the UI.
Status filter options are currently dynamically calculated from all observed statuses (possibly thousands of them). That is why, if you open about a 1000 of recommendations and apply all of them, these options will need to be recalculated about 1000 times (possibly millions of operations). This combined with frequent repainting makes it unacceptably slow.
I fixed them to all internal statuses instead, the statuses are now updating at least 2x faster (possibly much more than that) for larger page sizes.
=> Status filter options made constant: fixed #140

frontend/src/components/SavingsCostCell.vue
The solution proposed here is not as straightforward as it may seem. "none" is actually an invalid transition name, it could have been "nope" or "ice cream". What matters is that this removes all transitions, which is what we want.
The [solution](https://github.com/vuetifyjs/vuetify/issues/3453) proposed by a Vuetify contributor assumes the CSS class names (which I couldn't even find for v-tooltip). This confirms that there is probably no clean solution for this and I believe the one I am proposing is actually better because it is much simpler.
=> No tooltip transition. Fixes: #81

frontend/src/store/data_model/recommendation_extra.ts, frontend/src/store/recommendations.ts, frontend/tests/unit/apply.spec.ts
These are frontend changes needed for the `/checkStatus` endpoint update, as described below. Closes: #131 
The `/checkStatus` endpoint used to return `"NOT APPLIED", "SUCCEEDED", "FAILED" or "IN PROGRESS" `so there was no way  to check status on recommendations applied anywhere outside the app.
This endpoint has been updated and now returns` "CLAIMED"/"IN PROGRESS"/"ACTIVE"/"FAILED"/"SUCCEEDED" `(so it matches the Recommender API status names, and adds `"IN PROGRESS"` to mark recommendations that are in progress **and** have been applied by the Recomator).
=> checkStatus endpoint interface update

frontend/src/components/ResourceCell.vue, frontend/src/store/data_model/recommendation_raw.ts, frontend/src/store/utils/misc.ts, frontend/tests/unit/recommendations.spec.ts, frontend/tests/unit/sample_recommendation.ts
Adds Pantheon links for instances and disks. Closes: #152 
It is not that easy to make a test for Pantheon links for "INCREASE_PERFORMANCE" recommendations yet (not sent by the fake service), so I have created an issue to remember about this once we integrate with the real service when this will be much easier (#153).
First four commits are small tweaks to the related code, the last one contains the actual feature.
=> Frontend resource link

frontend/src/App.vue, frontend/src/main.ts, frontend/src/router/index.ts
- Starting fetching and status watchers has now been moved to router/index.ts so that they only launch when we are in the / route. This was not a problem when we had only one component, but we are about to add the permissions page which will need a new one.
- Removed the router link to / from each page (which caused the white space at the top, Fixes: #108)
=> Frontend move fetch

frontend/src/store/data_model/recommendation_extra.ts, frontend/src/store/data_model/recommendation_raw.ts, frontend/tests/unit/core_table.spec.ts, frontend/tests/unit/recommendations.spec.ts, frontend/tests/unit/sample_recommendation.ts
- "improve performance" recommendations have their cost computed properly now
- there used to be no tests for cost parsers, so added two for recommendations with cost in primaryImpact and additionalImpact respectively
=> Frontend fix cost parsers

frontend/src/config.ts, frontend/src/store/data_model/recommendation_extra.ts, frontend/src/store/recommendations.ts, frontend/src/store/utils/misc.ts
- We observed that one problem with parsing costs for "improve performance" recommendations made the whole app unusable, let's make sure that this doesn't happen again by wrapping the parsers in a try/catch block and printing the errors to the console instead.
- Changed the name of the backend address constant to reflect the fact that it is an address for backend not frontend (as this address would also make sense now in the context of this project). It is also better if the helper function is near the config, as this makes it much more local (although, it is best if we move these constants outside of src/ and into a proper constants-only config file at some point)
=> Frontend safer parsing

frontend/src/components/ResourceCell.vue, frontend/src/store/data_model/recommendation_raw.ts, frontend/tests/unit/recommendations.spec.ts, frontend/tests/unit/sample_recommendation.ts
- DELETE_DISK recommendations now have proper links (used to point to instances-like address)
- we want to open resource links in a new tab by default, it is way too easy to left-click it by mistake and to close the Recomator (restarting may take a really long time).
=> Two issues related to resource links

frontend/tests/unit/footer.spec.ts
One of the footer tests was broken, as it clicked the "Apply" buttons which triggered network requests (fetches).
The build didn't fail for the past few PRs to master because the error was in an async function, so only a warning which wrapped the error was shown. You can see it in build logs, for example: https://github.com/googleinterns/recomator/runs/1100333400 - open npm run test:unit.
The error:
`(node:2906) UnhandledPromiseRejectionWarning: ReferenceError: fetch is not defined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2906) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To …
=> Fix broken footer test: fetch needs to be disabled

frontend/tests/unit/recommendations.spec.ts
We used to return 404s once the pre-populated responses for the mock fetch have finished so that checkStatus calls do not fail the tests. But, they are no longer needed as we don't call checkStatus directly from fetch anymore, so these are nicely separated.
=> Frontend: simplify fetch tests

frontend/src/views/Home.vue
- If progress is 0 (which currently usually happens for a few seconds), the progress bar is set to the indeterminate mode so that the user knows that something is happening instead of seeing a nearly blank screen.
- ~~Changed the colour of the progress bar so that it doesn't match and blend in with the app bar~~
- We display "loading recommendations..." to help the user understand what is actually loading
First version (first commit): https://screencast.googleplex.com/cast/NDYzNjYwNjE4MDg4NDQ4MHw5OWM5ZTExOS0zZg
Second version (second commit): https://screencast.googleplex.com/cast/NTkwMzExNzkzNTcwNjExMnxiMjgxODQxOC0wYw
Looks okay on a mobile as well:
Closes: #179
=> Progress bar made more visible now

frontend/src/components/ProgressWithHeader.vue, frontend/src/views/Home.vue
The progress bar for fetching recommendations has just been moved to its own component.
This is done so that other operations, like fetching projects or requirements, can reuse it.
Closes: #198
=> New reusable progress + header component

frontend/src/components/ApplyAndStatusCell.vue
Before:
After:
I wasn't able to get breaking lines in the text of the error. Moreover, both errors that we have in the recommendations right now are empty.
=> Added styling to avoid line breaking

frontend/src/components/AppBar.vue, frontend/src/components/ProjectList.vue, frontend/src/components/ProjectsWithRequirements.vue, frontend/src/router/better_push.ts, frontend/src/views/Home.vue, frontend/src/views/Requirements.vue
We used to see errors like these whenever `router.push` was used and the route handler redirected somewhere else:
From what I read, these are not actually errors in the sense that we are using the Vue Router wrong. They are just hints that this *might* not be intended. Apparently, `<router-link>` implementation uses `router.push` in a way that just ignores these errors. I chose to just put them in the console, but not as red errors but as gray warnings. 
After:
Fixes: #210
=> Fix: Navigation exceptions in the console

frontend/src/components/AppBar.vue
I found an issue that projects is LocalStorage were overwritten to null when clicking 'Recomator'. Now it redirects to google sign in immediately.
=> fixed bug,clicking home from error page
